import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createAiDialogueService } from '../backend/ai-dialogue-server.mjs';
import { StoryClient } from '../web-runtime/story-client.mjs';

const cwd = resolve(process.cwd());
const root = cwd.endsWith('backend') ? resolve(cwd, '..') : cwd;
const packageData = JSON.parse(await readFile(resolve(root, 'data/story/story-package.json'), 'utf8'));
packageData.nodes.web_ai_test = { id: 'web_ai_test', type: 'ai_dialogue', title: 'AI 互动测试', speakerId: 'junior_sorcerer', fallbackSetId: 'junior_sorcerer_fallback', effectPolicyId: 'dialogue_only', maxTurns: 3, next: 'chapter1_map', completionRoutes: { normal: 'chapter1_map' } };
packageData.project.entryNodeId = 'web_ai_test';
const service = createAiDialogueService({ apiKey: '', contentPackage: packageData, dataDir: join(tmpdir(), `jjk-story-client-${process.pid}-${Date.now()}`) });
const fetchImpl = async (url, options = {}) => {
  const path = new URL(url, 'http://story.local').pathname;
  const body = options.body ? JSON.parse(options.body) : {};
  const result = await service.handle({ method: options.method || 'GET', path, body });
  return new Response(JSON.stringify(result.body), { status: result.status, headers: { 'content-type': 'application/json' } });
};
const received = [];
const client = new StoryClient({ packageData, fetchImpl, onEvents: (events) => received.push(...events) });
assert.ok(client.start().some((event) => event.type === 'start_ai_dialogue'));
const opened = await client.startAiDialogue({ saveId: 'save-1', nodeId: 'web_ai_test', npcId: 'junior_sorcerer' });
assert.equal(opened.source, 'local');
assert.equal(client.snapshot().aiSession.sessionId, opened.sessionId);
const turn = await client.sendAiTurn('我先观察现场再说明。');
assert.equal(turn.source, 'local');
assert.ok(turn.appliedEffects.length >= 1);
assert.ok(client.snapshot().growth.xp >= 1);
const resumeSnapshot = client.snapshot();
const resumed = new StoryClient({ packageData, snapshot: resumeSnapshot, fetchImpl, onEvents: (events) => received.push(...events) });
assert.equal(resumed.ai.sessionId, opened.sessionId);
await resumed.sendAiTurn('我继续观察残秽。');
const finalTurn = await resumed.sendAiTurn('最后再观察一次。');
assert.equal(finalTurn.sessionState, 'complete');
assert.equal(resumed.snapshot().currentNodeId, 'chapter1_map');
client.runtime = resumed.runtime;
client.ai = resumed.ai;
assert.equal(client.snapshot().growth.xp, 5, 'runtime must apply server-capped XP, not the raw proposal');
assert.equal(client.snapshot().aiSession, null);
assert.ok(received.some((event) => event.type === 'ai_dialogue_resolved'));
console.log(`WEB_STORY_CLIENT PASS source=${turn.source} revision=${turn.saveRevision} xp=${client.snapshot().growth.xp}`);
