export const ERROR_CATEGORIES = Object.freeze(['BOOTSTRAP', 'CONFIG', 'DATA', 'SCENE', 'INPUT', 'RULE', 'NETWORK', 'AUTH', 'ROOM', 'BATTLE', 'PERSISTENCE', 'WORKER', 'TEST', 'UNKNOWN']);
export const ERROR_CODES = Object.freeze({
  INVALID_REQUEST: 'INPUT', REQUEST_TOO_LARGE: 'INPUT', UNSUPPORTED_PROTOCOL_VERSION: 'CONFIG', ROUTE_NOT_FOUND: 'CONFIG',
  ROOM_NOT_FOUND: 'ROOM', ROOM_FULL: 'ROOM', NOT_ROOM_MEMBER: 'ROOM', NOT_ROOM_PLAYER: 'ROOM', HOST_REQUIRED: 'ROOM',
  ROOM_REVISION_CONFLICT: 'ROOM', MODE_NOT_ENABLED: 'ROOM', STALE_BATTLE_REVISION: 'BATTLE', BATTLE_NOT_READY: 'BATTLE',
  BATTLE_SNAPSHOT_MISSING: 'BATTLE', INVALID_STAGE: 'BATTLE', INVALID_STAGE_INPUT: 'INPUT', STAGE_INPUT_CONFLICT: 'BATTLE',
  CARD_NOT_IN_HAND: 'RULE', INSUFFICIENT_CE: 'RULE', DOMAIN_ALREADY_ACTIVE: 'RULE', INVALID_ROUND_INPUT: 'RULE',
  CHARACTER_SNAPSHOT_MISSING: 'DATA', CHECKPOINT_WRITE_FAILED: 'PERSISTENCE', WORKER_OVERLOADED: 'WORKER', INTERNAL_ERROR: 'UNKNOWN',
});

